### ISSUE TITLE
So can we get a new w+ vector based on style_space, latent and G  three parameters?

### ISSUE THREAD

**Issue by 123456klk1** [StelaBou/StyleMask#16]
![image](https://github.com/StelaBou/StyleMask/assets/53042912/5dba09d8-1446-4b4c-972e-2656fec28804)
Hello, your work is excellent!
I have a question I'd like to ask you.
You know, we can get the new image after editing the updated style vector guided by three parameters of S (stylegan2 space vector), the original image obtained by e4e latent space vector latent (w+) and stylegan2 generator.
So can we get a new w+ vector based on these three parameters?

**Comment by StelaBou** [comment]
Hi, just to make sure I understand your question correctly. Do you want to predict a new w+ latent code based on the edited style code? Could you please clarify what you mean by 'get a new w+ vector based on these three parameters'?

**Comment by 123456klk1** [comment]
yes, I want to predict a new w+ latent code based on the edited style code?

**Comment by StelaBou** [comment]
The w+ latent code remains the same when you edit the style code.

**Comment by 123456klk1** [comment]
The input is the style_space and latent. 
![image](https://github.com/StelaBou/StyleMask/assets/53042912/a32ff172-afe0-4494-a045-8f483755aeab)
Generally, the image can be generated according to the code of the above image, and then the image can be input into the e4e network to generate a new latent code. So can we get a new w+ vector based on style_space, latent, and G three parameters?
