### ISSUE TITLE
from libs.models.StyleGAN2-error

### ISSUE THREAD

**Issue by labels168** [StelaBou/StyleMask#4]
run_ inference. Error in line 19 of py
from libs.models.StyleGAN2.model import Generator as StyleGAN2Generator
I repeated the installation, confirmed the installation program, and carefully checked that there were no installation errors
I copied all databases to./pretrained_models
namely:
e4e_ffhq_encode_1024.pt
mask_network_1024.pt
stylegan2-ffhq-config-f_1024.pt

I don't know where I made a mistake. Ask for help. Thank you!
<img width="606" alt="ERROR" src="https://user-images.githubusercontent.com/58244515/205437900-49489349-3f34-44af-a2e0-9cae97758d7b.png">

**Comment by StelaBou** [comment]
Maybe [this issue](https://github.com/yfeng95/DECA/issues/122) can help you.
