### ISSUE TITLE
Where to use the DECA model

### ISSUE THREAD

**Issue by pfeducode** [StelaBou/StyleMask#7]
Hello, thank you for your excellent work. I have a question that I am not sure where you used the DECA model. The expression transfer in stylemask does not seem to be using the DECA method

**Comment by StelaBou** [comment]
Hello, 
the DECA model is used only during training in order to calculate the [shape loss](https://github.com/StelaBou/StyleMask/blob/67c455337a04a1892fc4a407cf3b0959e0f96a15/libs/trainer.py#L289). During inference you just need a pair of source and target images.
