### ISSUE TITLE
Inaccurate image reconstruction results outside of the ffhq dataset

### ISSUE THREAD

**Issue by pfeducode** [StelaBou/StyleMask#8]
I attempted to reconstruct using real photos but found that some of the reconstruction results were inaccurate. I am planning to do pre-training on my own dataset and noticed that you are using images generated from latent codes. However, StyleGAN2 cannot accurately generate the style space for images outside of FFHQ. Therefore, I am wondering how to solve this issue.
![actor14](https://user-images.githubusercontent.com/100210045/233537940-a94e83d7-60bb-4af4-a2f1-f7776ec718b6.png)
![2023-04-21_12-05](https://user-images.githubusercontent.com/100210045/233538497-5a9882dd-950c-4201-86e6-a4ed93a6c03c.png)
![grid_0000](https://user-images.githubusercontent.com/100210045/233537956-14476edb-882d-4f14-a9f5-50ef1dc05517.png)

**Comment by StelaBou** [comment]
In order to invert real images into the latent space of StyleGAN2 I am using [e4e](https://github.com/omertov/encoder4editing) inversion method. This method is able to produce high-quality reconstructions however when the real images are far away from the distribution of FFHQ dataset, the results are not good. One solution is to try a better inversion method and then check if it is possible to edit the inverted images.

**Comment by pfeducode** [comment]
> In order to invert real images into the latent space of StyleGAN2 I am using [e4e](https://github.com/omertov/encoder4editing) inversion method. This method is able to produce high-quality reconstructions however when the real images are far away from the distribution of FFHQ dataset, the results are not good. One solution is to try a better inversion method and then check if it is possible to edit the inverted images.

There is currently a new method https://github.com/danielroich/PTI that is more accurate than e4e, but it uses stylegan2 ada and I am not sure if it is applicable to your code

**Comment by StelaBou** [comment]
You can first use the e4e method to get the initial inverted latent code and then use PTI to  optimize the generator's weights to get a better reconstruction. You can then use my method to edit the inverted images. However, as PTI changes the generator's weights there maybe some issues when editing the style space.

**Comment by pfeducode** [comment]
> 可以先用e4e的方法得到初始的inverted latent code，然后用PTI优化生成器的权重，得到更好的重构。然后您可以使用我的方法来编辑倒置图像。但是，由于 PTI 会更改生成器的权重，因此在编辑样式空间时可能会出现一些问题。

Why is there jitter during the generation of videos

**Comment by StelaBou** [comment]
Since our model is  trained on image editing, there is no way to ensure temporal consistency when generating videos. As a result, some jittering may be present.

**Comment by pfeducode** [comment]
Hello, integrating PTI requires changing the network model. If I want to obtain image reconstruction outside the ffhq domain, I would like to continue training and fine-tuning the model based on the MaskNet network. Is this method possible to succeed.
