### ISSUE TITLE
Image resolution

### ISSUE THREAD

**Issue by r1a0r** [StelaBou/StyleMask#9]
Hi,
Is it possible to generate 1024x1024 image?

**Comment by StelaBou** [comment]
Yes, I am using StyleGAN2 model trained on 1024x1024 image resolution. I 'm just resizing the images into 256 resolution for visualization purposes.

**Comment by StelaBou** [comment]
You need to change the argument resize_image on inference script. Check [here](https://github.com/StelaBou/StyleMask/blob/792f644bbb4926906df99d1bd77e873ade5cdc3b/run_inference.py#L163). 

I added now resize_image on arguments list so if you run: 
`python run_inference.py  --output_path ./results --save_image`
it will save the images into 1024x1024 resolution, while if you run
`python run_inference.py  --output_path ./results --save_image --resize_image`
it will save the images into 256x256 resolution.
